### ISSUE TITLE
LB remains OFFLINE as long as other LB is erroneous

### ISSUE THREAD

**Issue by laerlingSAP** [sapcc/octavia-f5-provider-driver#111]
### Steps to reproduce
1) Create a loadbalancer that is erroneous (before [Octavia PR #2](https://github.com/sapcc/octavia/pull/2) is merged, this can be achieved by creating a member with the same address as the LB).
2) Create a second LB in the same project that is not erroneous

### Expected behavior
The second loadbalancer is created (and comes `ONLINE`) without respect to the first erroneous LB.

### Observed behavior
Both loadbalancers are being provisioned within the same AS3 declaration. Due to the first one being erroneous, the declaration fails. Thus, the second LB remains `OFFLINE`.

### Proposed fix
Separate AS3 declarations somehow. For example, first create a declaration for everything that's `PENDING_CREATE` and then (and only then) for everything that's `PENDING_UPDATE`.

**Comment by notandy** [comment]
> ### Proposed fix
> Separate AS3 declarations somehow. For example, first create a declaration for everything that's `PENDING_CREATE` and then (and only then) for everything that's `PENDING_UPDATE`.

#Wontfix #notpossible
AS3 tenants are the smallest possible declaration you can submit, so the bugfix is to detect and handle any issues that occur with a declaration.
