### ISSUE TITLE
Enforce upper limit of 3600s for health monitor delay

### ISSUE THREAD

**Issue by BenjaminLudwigSAP** [sapcc/octavia-f5-provider-driver#140]
HMs don't support more. LB will get stuck in `PENDING_UPDATE`.

**Comment by BenjaminLudwigSAP** [comment]
Maybe use pre-commit hook on API side like in Neutron.

Edit:
No. Pre-commit hooks are ml2-specific, Octavia doesn't have ml2.
I could use Pecan hooks, but there is a way to do it completely in the driver: [health_monitor_create](https://github.com/sapcc/octavia-f5-provider-driver/blob/stable/yoga-m3/octavia_f5/api/drivers/f5_driver/driver.py#L176)

Edit: Implementing it in the [driver component of F5 PD](https://github.com/sapcc/octavia-f5-provider-driver/blob/stable/yoga-m3/octavia_f5/api/drivers/f5_driver/driver.py#L176-L193) makes most sense. It runs in the API, but is not part of API/upstream code, and it runs before the DB transaction is even committed, so that pre-commit checks can be run here.

**Comment by m-kratochvil** [comment]
For clarity of terms:
Octavia `delay` = AS3 `interval` (class "Monitor") = Big-IP `interval`
