### ISSUE TITLE
Delete hardcoding persist time out in irule

### ISSUE THREAD

**Issue by sungwon-ahn** [sapcc/octavia-f5-provider-driver#158]
Hello, I'm interested in the project, I'm leaving an issue with one suggestion.

Although openstack octavia does not support the options for "persist time out", I think it is not desirable that the time out value is hardcoded in the code adding the irule.

The issues are as follows:

(https://github.com/sapcc/octavia-f5-provider-driver/blob/stable/ussuri-m3/octavia_f5/restclient/as3objects/irule.py#L157)

```
def get_app_cookie_irule(cookie_name):
    """
    Returns iRule for app cookie persistance with cookie_name.
    :return: iRule entity (tuple with iRule name and definition)
    """
    app_cookie_irule = APP_COOKIE_SESSION_PERSIST.format(_cookie=cookie_name)
    irule = IRule(app_cookie_irule,
                  remark="Persistance app cookie")
    name = '{}app_cookie_{}'.format(constants.PREFIX_IRULE, cookie_name)
    return name, irule

```

```
APP_COOKIE_SESSION_PERSIST = """when HTTP_REQUEST {{
    if {{ [HTTP::cookie exists "{_cookie}"] }} {{
        persist uie [HTTP::cookie "{_cookie}"] 3600
    }}
}}
when HTTP_RESPONSE {{
    if {{ [HTTP::cookie exists "{_cookie}"] }} {{
        persist add uie [HTTP::cookie "{_cookie}"] 3600
    }}
}}"""
```

**Comment by BenjaminLudwigSAP** [comment]
Hello, thanks for the issue. Is this due to a specific use case you have or just a general recommendation?

**Comment by sungwon-ahn** [comment]
Hello, This is because of general recommendations. 

Time out through Octavia API is not supported. But F5 is supported
I think it is correct to support that part in the form of a config file.

**Comment by BenjaminLudwigSAP** [comment]
The idea is good, thank you.
However I want to introduce new code only when it is definitely needed.
I will close this issue and change the code when the need to parameterize this occurs.
Of course anyone actually using octavia-f5-provider-driver who needs this can feel free to send a PR.

**Comment by BenjaminLudwigSAP** [comment]
In case I ever take this up again: The hardcoded value probably has to be changed in some other places as well:
```
$ grep -rIF 3600
octavia_f5/restclient/as3objects/irule.py:        persist uie [HTTP::cookie "{_cookie}"] 3600
octavia_f5/restclient/as3objects/irule.py:        persist add uie [HTTP::cookie "{_cookie}"] 3600
octavia_f5/restclient/as3objects/persist.py:        duration=3600
octavia_f5/restclient/bigip/bigip_auth.py:BIGIP_TOKEN_MAX_TIMEOUT = '36000'
octavia_f5/common/config.py:    cfg.IntOpt('cache_time', default=3600,
octavia_f5/common/config.py:               help=_('Caching time in seconds (default=3600)')),
```
