### ISSUE TITLE
Slow queries because of growing amphora table

### ISSUE THREAD

**Issue by notandy** [sapcc/octavia-f5-provider-driver#199]
The Amphora table that is used by every loadbalancer doesn't get cleaned up correctly and grows indefinitely, causing at some point slow queries.

**Comment by m-kratochvil** [comment]
As a complete python noob I'm trying to "decipher" what the code [HERE](https://github.com/sapcc/octavia-f5-provider-driver/blob/418bbdadd8bd1c7eca47e6340ae1f8de651b8771/octavia_f5/controller/statusmanager/status_manager.py#L376) is doing. So far I don't see anything wrong but will continue trying for a bit more before I give up :-)

**Comment by notandy** [comment]
True, maybe you'd like to debug this code part and see if it's executed as expected?

**Comment by m-kratochvil** [comment]
Let me lay out what I understand from looking at the pieces of code involved in the cleanup, I hope that I'm at least partially right.

From [THIS](https://github.com/sapcc/octavia-f5-provider-driver/blob/607d892f01a8741428ff95f2b1a655ef2b7e31bf/octavia_f5/common/config.py#L218) snippet I derived that the cleanup interval is 600s (10 minutes):
```
 cfg.IntOpt('cleanup_check_interval',
               default=60*10,
               help=_('Sleep time between cleanup checks in seconds.')),
```

[HERE](https://github.com/sapcc/octavia-f5-provider-driver/blob/418bbdadd8bd1c7eca47e6340ae1f8de651b8771/octavia_f5/controller/statusmanager/status_manager.py#L86), the `_last_cleanup_check` value is initialized at 0
```
        self._last_cleanup_check = 0
```

Execution of the `cleanup()` task is then defined in the [`heartbeat()`](https://github.com/sapcc/octavia-f5-provider-driver/blob/418bbdadd8bd1c7eca47e6340ae1f8de651b8771/octavia_f5/controller/statusmanager/status_manager.py#L206) function. Pseudocode would be:
If current epoch value minus `_last_cleanup_check` is greater or equal the cleanup interval (600), set the `_last_cleanup_check` value to current epoch value and execute the `cleanup()` function.
```
        if time.time() - self._last_cleanup_check >= CONF.status_manager.cleanup_check_interval:
            self._last_cleanup_check = time.time()
            self.cleanup()
```

The [`cleanup()`](https://github.com/sapcc/octavia-f5-provider-driver/blob/418bbdadd8bd1c7eca47e6340ae1f8de651b8771/octavia_f5/controller/statusmanager/status_manager.py#L376) function itself looks ok to me, it gets a session to DB, extracts the `DELETED` loadbalancers from amphora table and deletes them.
```
    def cleanup(self):
        """ Deletes old amphora entries whose load balancers don't exist anymore.
        See controller_worker.ensure_amphora_exists for details.
        """
        with DatabaseLockSession() as session:
            filters = {'load_balancer_id': None, 'cached_zone': None, 'compute_flavor': CONF.host,}
            try:
                self.amp_repo.delete(session, **filters)
            except sqlalchemy.exc.InvalidRequestError:
                pass
```

The `heartbeat()` function is executed as part of the [`periodic_status()`](https://github.com/sapcc/octavia-f5-provider-driver/blob/418bbdadd8bd1c7eca47e6340ae1f8de651b8771/octavia_f5/cmd/status_manager.py#L71) function, which is executed as part of the `main()` function in the `status_manager.py` script.

I don't see an obvious issue, the only suspicious part to me is the cleanup interval value being set to `60*10`, I wonder why is it set like that, and not straight to "600", if it could possibly be causing an issue.

So yes, I'd like to debug the code, or I should rather say watch you or @BenjaminLudwigSAP debug it, as I don't have a way to execute a code like this yet.
