### ISSUE TITLE
Source IP persistence removal via UI

### ISSUE THREAD

**Issue by m-kratochvil** [sapcc/octavia-f5-provider-driver#221]
* *  This issue may be better fit for Elektra repository * *

Source IP persistence can't be removed via Elektra, it's stubbornly staying configured on a pool.
Removal working fine via CLI. API untested but presumed working. This seems like Elektra issue.

@ArtieReus , can you please test it from your end as well and confirm? You can use following pool as a guinea pig:
https://dashboard.qa-de-1.cloud.sap/monsoon3/d071955-testing/lbaas2/?r=/loadbalancers/487e7950-d600-483c-9493-89206f2f338b/show?pool=50fb3f12-aae9-44dd-9840-594b96d8fdbf

**Comment by m-kratochvil** [comment]
Discussed with Arturo, bugs acknowledged, fix pending.

**Comment by ArtieReus** [comment]
I can reproduce it. Fix is on the way. Thx!!

**Comment by ArtieReus** [comment]
This should be fixed now.

**Comment by m-kratochvil** [comment]
It behaves weird now, when I try to remove the persistence from a pool (any persistence type), by clicking the "X" in the persistence field, then after clicking the "Save" button, it gets forever stuck on "Please Wait ..."

![image](https://github.com/sapcc/octavia-f5-provider-driver/assets/43531504/b52e818f-8312-4555-a14f-9be661bdc800)

**Comment by ArtieReus** [comment]
Can you reproduce it? If it stucks on updating is probably because no response is comming.

**Comment by ArtieReus** [comment]
I tested in `eu-de-1` and it works fine for me but it octavia seems to be very slow.

**Comment by m-kratochvil** [comment]
I created a pool in ap-jp-2 cc-demo project, and I get the same issue there..
https://dashboard.ap-jp-2.cloud.sap/monsoon3/cc-demo/lbaas2/?r=/loadbalancers/1dbb0dc5-1648-4dbe-9d97-b864887cc1a3/show?pool=573f26fd-78d4-41ff-bbaf-672294f04c86

**Comment by m-kratochvil** [comment]
Working as expected now, see https://convergedcloud.slack.com/archives/DAKAA5FB8/p1690973515997729 for details.
