### ISSUE TITLE
L7 policy custom redirect code ignored

### ISSUE THREAD

**Issue by m-kratochvil** [sapcc/octavia-f5-provider-driver#249]
Customer reported (Slack) that custom redirect code in an L7 policy is not reflected in the AS3/Big-IP configuration.

Example:
Policy action: REDIRECT_TO_URL
Redirect HTTP Code: 308
Redirect Url: <some URL>

Results in the default redirect code 302 configured on the Big-IP.

**Comment by BenjaminLudwigSAP** [comment]
The policy is handled [here in the code](https://github.com/sapcc/octavia-f5-provider-driver/blob/stable/yoga-m3/octavia_f5/restclient/as3objects/policy_endpoint.py#L101-L104). It sets AS3 parameters `type` (to `httpRedirect`), `location` and `event` (to `request`).
I don't think it's possible to set a custom redirect code in AS3, though I might be wrong. I think we have talked about this before, haven't we?

**Comment by BenjaminLudwigSAP** [comment]
AS3 knows the `Policy_Action_HTTP_Redirect` object with the `code` parameter.

**Comment by m-kratochvil** [comment]
Handed over to @velp as I have no time at the moment.

**Comment by BenjaminLudwigSAP** [comment]
Fix rolled out globally.
