### ISSUE TITLE
Enable new cipher support

### ISSUE THREAD

**Issue by m-kratochvil** [sapcc/octavia-f5-provider-driver#253]
Requested by HxM via Jira
Cipher requested: `ECDHE-RSA-CHACHA20-POLY1305-SHA256`
Protocol: TLSv1.2

Progress and more details in the above JIRA ticket.

**Comment by m-kratochvil** [comment]
Cipher evaluated via ssllabs, rating "A", marked as "secure". We can support it.

**Comment by m-kratochvil** [comment]
Created PR for integrating the new cipher

**Comment by BenjaminLudwigSAP** [comment]
That PR has been reviewed, approved, merged, rolled out.
