### ISSUE TITLE
Wrongly named SelfIP ports

### ISSUE THREAD

**Issue by BenjaminLudwigSAP** [sapcc/octavia-f5-provider-driver#254]
Apparently Octavia F5PD sometimes creates SelfIP ports with the subnet ID missing from the name.

# Steps to reproduce
Not yet known.

# Expected behavior
All SelfIP ports have a name that ends with the subnet ID, e.g. `local-REGIONNAME-F5NAME.domain.tld-00000000-0000-0000-0000-000000000000`.

# Observed behavior
Some SelfIP ports have a name that does not end with the subnet ID, e.g. `local-REGIONNAME-F5NAME.domain.tld`.

# Notes
It's interesting that not even the dash after the TLD is there.

**Comment by notandy** [comment]
This is a red herring, they are not not octavia selfips.
