### ISSUE TITLE
Trigger ESDs via something else than specially named L7policies

### ISSUE THREAD

**Issue by notandy** [sapcc/octavia-f5-provider-driver#35]
We use F5 ESDs (Enhanced Services Definitions) to extend LB functionality beyond L7 policies.
In F5 neutron-lbaas plugin those ESDs are triggered by creating a L7policy with the same name as the ESD.
This leads to L7rules within the L7policy being ignored, thus abusing the whole idea of L7 policies. 

That's why we want to trigger ESDs with something else than L7policies and get rid of ESDs, if necessary.

---

We tried using [Octavia Flavors](https://docs.openstack.org/octavia/latest/admin/flavors.html) instead, but every LB can only use one flavor.

A better idea is to use tags.
Tags can be used on the following Octavia objects:
- loadbalancer
- listener
- pool
- member
- L7rule
- L7policy
- healthmonitor

**Comment by laerlingSAP** [comment]
The ESD definitions we're currently using:
```
{
  "proxy_protocol_2edF_v1_0": {
    "lbaas_fastl4": "",
    "lbaas_ctcp": "tcp",
    "lbaas_irule": ["proxy_protocol_2edF_v1_0"],
    "lbaas_one_connect": ""
  },
  "proxy_protocol_V2_e8f6_v1_0": {
    "lbaas_fastl4": "",
    "lbaas_ctcp": "tcp",
    "lbaas_irule": ["cc_proxy_protocol_V2_e8f6_v1_0"],
    "lbaas_one_connect": ""
  },
  "standard_tcp_a3de_v1_0": {
    "lbaas_fastl4": "",
    "lbaas_ctcp": "tcp",
    "lbaas_one_connect": ""
  },
  "x_forward_5b6e_v1_0": {
    "lbaas_irule": ["cc_x_forward_5b6e_v1_0"]
  },
  "one_connect_dd5c_v1_0": {
    "lbaas_one_connect": "oneconnect"
  },
  "no_one_connect_3caB_v1_0": {
    "lbaas_one_connect": ""
  },
  "http_compression_e4a2_v1_0": {
    "lbaas_http_compression": "cc_http_compression_e4a2_v1_0"
  },
  "cookie_encryption_b82a_v1_0": {
    "lbaas_irule": ["cc_cookie_encryption_b82a_v1_0"]
  },
  "sso_22b0_v1_0": {
    "lbaas_irule": ["cc_sso_22b0_v1_0"]
  },
  "sso_required_f544_v1_0": {
    "lbaas_irule": ["cc_sso_required_f544_v1_0"]
  },
  "http_redirect_a26c_v1_0": {
    "lbaas_irule": ["cc_http_redirect_a26c_v1_0"]
  }
}
```

The following ESDs do not have to be translated to Octavia flavors, because Octavia already implements their functionality:
| ESD | Octavia concept |
|-|-|
| proxy_protocol_2edF_v1_0 | proxy listener |
| x_forward_5b6e_v1_0 | listener property 'insert_header' o. Ä. |
| http_redirect_a26c_v1_0 | L7 rule |
