### ISSUE TITLE
Make status_manager aware which bigIP is active

### ISSUE THREAD

**Issue by notandy** [sapcc/octavia-f5-provider-driver#42]
Currently status_manager scrapes statistics from a single bigip, but since they can failover or even run in an active-active scenario, the status manager needs to scrape both device pairs and figure out what to submit

Related to #4

**Comment by laerlingSAP** [comment]
Status manager supports only one F5 as of now, has to support both.
F5s have statistic export, which is imported by status manager. Unknown how this behaves at failover.
Statistics don't seem to be synchronized between BigIPs. Are statistics reset at failover?
Can this be synchronized? Does it make sense? Or does it suffice to pull statistics only from active BigIP?

**Comment by laerlingSAP** [comment]
F5s have statistic export, which is imported by status manager. Unknown how this behaves at failover. Statistics don't seem to be synchronized between BigIPs. Are statistics reset at failover?
Can this be synchronized? Does it make sense? Or does it suffice to pull statistics only from active BigIP?

**Comment by laerlingSAP** [comment]
Inspiration: [Code in neutron-lbaas that determines the failover state](https://github.com/sapcc/neutron-lbaas/blob/7fe6994cf1cbdfa27b3b96565a50cd48358178d3/tools/nlbaas2octavia/nlbaas2octavia.py#L94)
