### ISSUE TITLE
Scenario: Disappearing/reappearing device

### ISSUE THREAD

**Issue by laerlingSAP** [sapcc/octavia-f5-provider-driver#61]
Scenario: Device disappears (maintenance, ...), comes back online after 1h or so.
Full sync needed. Automate that.

**Comment by notandy** [comment]
Health monitors of status_manager gets reappering device -> updates device-pair entry in amphora table (loadbalancer_id == NULL, status == READY, compute_flavor == <host_id>

octavia-worker picks up and does a full sync.

**Comment by laerlingSAP** [comment]
Test whether only the tenant is updated or all tenants.
