### ISSUE TITLE
Write docs: README, configuration, setup

### ISSUE THREAD

**Issue by jsm222** [sapcc/octavia-f5-provider-driver#77]
Hi, I'm pleased to find this software. However it is a little cumbersome, to read all the python code, to get an idea of how it is supposed to be configured, where do I find some documentation?

Thx

**Comment by laerlingSAP** [comment]
It is planned to write an extensive README. I'll make this the tracking issue for that.

**Comment by laerlingSAP** [comment]
First version of README in #78

**Comment by laerlingSAP** [comment]
@jsm222 A makeshift README has been added. I'll be closing this issue.
Please write another comment if there is any particular information you're missing in the README and I'll reopen this issue if appropriate. Thank you :)
